### ISSUE TITLE
Amélioration dashboard de popularité

### ISSUE THREAD

**Issue by rlouf** [AlexAndorra/pollsposition_dashboards#1]
## Model

- [ ] Modéliser et présenter le % d'opinions positives;
- [ ] Modéliser au jour-le-jour

## Dashboard

- [ ] Liste des sondages en bas de page
- [ ] Courbe devrait être sur les points
- [ ] Texte avec une bordure blanche directement sur la courbe
- [ ] Plus belle présentation des sondage quand la souris passe sur le point
- [ ] Redimensionnement avec la taile de la page
- [ ] Comparaison avec les anciens président dynamique et affiche le % de popularite

**Comment by AlexAndorra** [comment]
Tranferred over at https://github.com/pollsposition/dashboards/issues/1
